# Defines the location of the EZ-USB SDK
ZTEXPREFIX=../..

# The name of the jar archive
JARTARGET=Fx3Demo.jar
# Java Classes that have to be build 
CLASSTARGETS=Fx3Demo.class
# Extra dependencies for Java Classes
CLASSEXTRADEPS=$(IMGTARGETS)

# img files (firmware ROM files) that have to be build 
IMGTARGETS=fx3demo.img
EXTRA_C_SOURCES=
EXTRA_A_SOURCES=

# Extra files that should be included into th jar archive
EXTRAJARFILES=fx3demo.img

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk

