#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX=../../sdk

# The name of the jar archive
JARTARGET=wpa2.jar
# Java Classes that have to be build 
CLASSTARGETS=wpa2.class
# Extra dependencies for Java Classes
CLASSEXTRADEPS=

# ihx files (firmware ROM files) that have to be built 
IHXTARGETS=wpa2.ihx
# Extra Dependencies for ihx files
IHXEXTRADEPS=

# Extra files that should be included into th jar archive
#EXTRAJARFILES=wpa2.ihx ../hdl/wpa2.bit

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
