# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /drv_s2/usb-fpga/ztex/examples/usb-fpga-2.13/2.13b/memfifo/fpga/memfifo.xdc

# IP: ip/mig_7series_0/mig_7series_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0}]

# XDC: ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0}]

# XDC: ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc
