#########################
# configuration section #
#########################

ZTEXPREFIX=../..

JARTARGET=Default.jar
CLASSTARGETS=Default.class
CLASSEXTRADEPS=

# img files (firmware ROM files) that have to be build 
IMGTARGETS=default.img
EXTRA_C_SOURCES=
EXTRA_A_SOURCES=

# Extra files that should be included into th jar archive
EXTRAJARFILES=default.img

default: all

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk

