#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX=../..

# The name of the jar archive
JARTARGET=MemFifo.jar
# Java Classes that have to be build 
CLASSTARGETS=MemFifo.class
# Extra dependencies for Java Classes
CLASSEXTRADEPS=

# img files (firmware ROM files) that have to be build 
IMGTARGETS=
EXTRA_C_SOURCES=
EXTRA_A_SOURCES=

# Extra files that should be included into th jar archive
EXTRAJARFILES=fpga-2.01b/memfifo.bit \
              fpga-2.04b/memfifo.bit \
              fpga-2.13/memfifo.runs/impl_2_13a/memfifo.bit \
              fpga-2.13/memfifo.runs/impl_2_13b/memfifo.bit \
              fpga-2.13/memfifo.runs/impl_2_13c/memfifo.bit \
              fpga-2.13/memfifo.runs/impl_2_13d/memfifo.bit \
              fpga-2.14/memfifo.runs/impl_2_14a/memfifo.bit \
              fpga-2.14/memfifo.runs/impl_2_14b/memfifo.bit \
              fpga-2.14/memfifo.runs/impl_2_14c/memfifo.bit \
              fpga-2.14/memfifo.runs/impl_2_14d/memfifo.bit \
              fpga-2.14/memfifo.runs/impl_2_14e/memfifo.bit \
              fpga-2.16/memfifo.runs/impl_2_16b/memfifo.bit

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
