#!/bin/bash
DIR=${0%/*}
if [ -r $DIR/DefaultUpdater.jar ]; then
    java -cp $DIR/DefaultUpdater.jar DefaultUpdater $@
else 
    export CLASSPATH=$CLASSPATH:/usr/local/share/java:/usr/share/java
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib
    java DefaultUpdater $@
fi    
