#########################
# configuration section #
#########################

ZTEXPREFIX=../..

JARTARGET=DefaultUpdater.jar
CLASSTARGETS=DefaultUpdater.class
CLASSEXTRADEPS=

IHXTARGETS=
IHXEXTRADEPS=
EXTRAJARFILES=
EXTRADISTCLEANFILES=

default: all

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk

