#########################
# configuration section #
#########################

ZTEXPREFIX=../..

JARTARGET=Fx2Demo.jar
CLASSTARGETS=Fx2Demo.class
CLASSEXTRADEPS=
#CLASSEXTRADEPS:=$(wildcard $(ZTEXPREFIX)/java/ztex/*.java)

IHXTARGETS=fx2demo.ihx
IHXEXTRADEPS=
#IHXEXTRADEPS:=$(wildcard $(ZTEXPREFIX)/include/*.h)
EXTRAJARFILES=fx2demo.ihx

################################
# DO NOT CHANAGE THE FOLLOWING #
################################

include $(ZTEXPREFIX)/Makefile.mk
