#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX=../..

# The name of the jar archive
JARTARGET=UCEcho.jar
# Java Classes that have to be build 
CLASSTARGETS=UCEcho.class
# Extra dependencies for Java Classes
CLASSEXTRADEPS=

# img files (firmware ROM files) that have to be build 
IMGTARGETS=
EXTRA_C_SOURCES=
EXTRA_A_SOURCES=

# Extra files that should be included into th jar archive
EXTRAJARFILES=fpga-2.01b/ucecho.bit \
              fpga-2.04b/ucecho.bit \
              fpga-2.13/ucecho.runs/impl_2_13a/ucecho.bit \
              fpga-2.13/ucecho.runs/impl_2_13b/ucecho.bit \
              fpga-2.13/ucecho.runs/impl_2_13c/ucecho.bit \
              fpga-2.13/ucecho.runs/impl_2_13d/ucecho.bit \
              fpga-2.14/ucecho.runs/impl_2_14a/ucecho.bit \
              fpga-2.14/ucecho.runs/impl_2_14b/ucecho.bit \
              fpga-2.14/ucecho.runs/impl_2_14c/ucecho.bit \
              fpga-2.14/ucecho.runs/impl_2_14d/ucecho.bit \
              fpga-2.14/ucecho.runs/impl_2_14e/ucecho.bit \
              fpga-2.16/ucecho.runs/impl_2_16b/ucecho.bit

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
