#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX=../..

# The name of the jar archive
JARTARGET=MMIO.jar
# Java Classes that have to be build 
CLASSTARGETS=MMIO.class
# Extra dependencies for Java Classes
CLASSEXTRADEPS=

# ihx files (firmware ROM files) that have to be build 
IHXTARGETS=mmio-2_16.ihx
# Extra Dependencies for ihx files
IHXEXTRADEPS=

# Extra files that should be included into th jar archive
EXTRAJARFILES=mmio-2_16.ihx fpga-2.16/mmio.runs/impl_2_16b/mmio.bit

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
